var e = [ {
    SubjectEntities: [ {
        SubjectName: "初级会计职称",
        SubjectParentId: 49,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 3
    }, {
        SubjectName: "中级会计职称",
        SubjectParentId: 49,
        IsNeed: 0,
        SubjectLevel: 1,
        SearchNames: null,
        SubjectLevelId: 4
    }, {
        SubjectName: "注册会计师",
        SubjectParentId: 70,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "会计从业实训",
        SubjectParentId: 422,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "初级经济师",
        SubjectParentId: 14,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 1
    }, {
        SubjectName: "中级经济师",
        SubjectParentId: 14,
        IsNeed: 1,
        SubjectLevel: 1,
        SearchNames: null,
        SubjectLevelId: 2
    } ],
    GroupName: "会计类",
    SubjectShortNames: "会计从业  会计初级 中级 注会  经济师",
    ImgUrl: "http://img02.exam8.com/wantiku/ios/caikuai1.png",
    GroupId: 8
}, {
    SubjectEntities: [ {
        SubjectName: "一建",
        SubjectParentId: 3,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "二建",
        SubjectParentId: 7,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    } ],
    GroupName: "建造类",
    SubjectShortNames: "一建  二建",
    ImgUrl: "http://img02.exam8.com/wantiku/ios/gongcheng1.png",
    GroupId: 20
}, {
    SubjectEntities: [ {
        SubjectName: "一建",
        SubjectParentId: 3,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "二建",
        SubjectParentId: 7,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "造价师",
        SubjectParentId: 8,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "安全工程师",
        SubjectParentId: 493,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "电气工程师",
        SubjectParentId: 503,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "招标师",
        SubjectParentId: 498,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "一级消防工程师",
        SubjectParentId: 515,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 9
    }, {
        SubjectName: "二级消防工程师",
        SubjectParentId: 515,
        IsNeed: 0,
        SubjectLevel: 1,
        SearchNames: null,
        SubjectLevelId: 10
    }, {
        SubjectName: "测绘师",
        SubjectParentId: 540,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "房产估价师",
        SubjectParentId: 544,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    } ],
    GroupName: "工程类",
    SubjectShortNames: "一建  二建  造价  安全  电气  招标  消防",
    ImgUrl: "http://img02.exam8.com/wantiku/ios/gongcheng1.png",
    GroupId: 4
}, {
    SubjectEntities: [ {
        SubjectName: "执业护士",
        SubjectParentId: 454,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "护师",
        SubjectParentId: 804,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "执业药师",
        SubjectParentId: 404,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "执业医师",
        SubjectParentId: 441,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "初级卫生资格（师）",
        SubjectParentId: 459,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 5
    }, {
        SubjectName: "中级卫生资格（主治）",
        SubjectParentId: 459,
        IsNeed: 1,
        SubjectLevel: 1,
        SearchNames: null,
        SubjectLevelId: 7
    }, {
        SubjectName: "中级卫生资格（主管）",
        SubjectParentId: 459,
        IsNeed: 1,
        SubjectLevel: 2,
        SearchNames: null,
        SubjectLevelId: 8
    } ],
    GroupName: "医学类",
    SubjectShortNames: "执业护士  药师  医师  卫生资格",
    ImgUrl: "http://img02.exam8.com/wantiku/ios/yiliao1.png",
    GroupId: 9
}, {
    SubjectEntities: [ {
        SubjectName: "公务员",
        SubjectParentId: 432,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "事业单位",
        SubjectParentId: 715,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    } ],
    GroupName: "公考类",
    SubjectShortNames: "公务员 事业单位",
    ImgUrl: "http://img02.exam8.com/wantiku/ios/gongzhi.png",
    GroupId: 13
}, {
    SubjectEntities: [ {
        SubjectName: "自考",
        SubjectParentId: 549,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "成人高考(高中起点升本科、专科)",
        SubjectParentId: 649,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 11
    }, {
        SubjectName: "成人高考(专科起点升本科)",
        SubjectParentId: 649,
        IsNeed: 1,
        SubjectLevel: 1,
        SearchNames: null,
        SubjectLevelId: 12
    }, {
        SubjectName: "考研",
        SubjectParentId: 417,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    } ],
    GroupName: "学历类",
    SubjectShortNames: "考研  自考  成考",
    ImgUrl: "http://img02.exam8.com/wantiku/ios/daxue1.png",
    GroupId: 10
}, {
    SubjectEntities: [ {
        SubjectName: "人力资源",
        SubjectParentId: 650,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "初级社会工作者",
        SubjectParentId: 795,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "中级社会工作者",
        SubjectParentId: 795,
        IsNeed: 0,
        SubjectLevel: 1,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "心理咨询",
        SubjectParentId: 651,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "司法考试",
        SubjectParentId: 12,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    } ],
    GroupName: "资格类",
    SubjectShortNames: "四六级 司考 心理 人力 社会工作者 职称英语",
    ImgUrl: "http://img02.exam8.com/wantiku/ios/zige1.png",
    GroupId: 6
}, {
    SubjectEntities: [ {
        SubjectName: "英语四六级",
        SubjectParentId: 83,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    } ],
    GroupName: "外语类",
    SubjectShortNames: "四六级 司考 心理 人力 社会工作者 职称英语",
    ImgUrl: "http://img02.exam8.com/wantiku/ios/zige1.png",
    GroupId: 15
}, {
    SubjectEntities: [ {
        SubjectName: "基金从业",
        SubjectParentId: 532,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "证券从业",
        SubjectParentId: 58,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "银行从业",
        SubjectParentId: 435,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "银行招聘",
        SubjectParentId: 721,
        IsNeed: 1,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    }, {
        SubjectName: "期货从业",
        SubjectParentId: 528,
        IsNeed: 0,
        SubjectLevel: 0,
        SearchNames: null,
        SubjectLevelId: 0
    } ],
    GroupName: "金融类",
    SubjectShortNames: "基金  证券  银行从业  银行招聘  期货",
    ImgUrl: "http://img02.exam8.com/wantiku/ios/jinrong1.png",
    GroupId: 11
} ];

module.exports = e;